apiVersion: jobset.x-k8s.io/v1alpha2
kind: JobSet
metadata:
  annotations:
    alpha.jobset.sigs.k8s.io/exclusive-topology: cloud.google.com/gke-nodepool
  name: maxtext-multislice-105
  namespace: tpu-training
spec:
  failurePolicy:
    maxRestarts: 1
  replicatedJobs:
  - name: slice
    replicas: 2
    template:
      spec:
        backoffLimit: 0
        completions: 2
        parallelism: 2
        template:
          spec:
            affinity:
              podAffinity:
                requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchExpressions:
                    - key: jobset.sigs.k8s.io/jobset-name
                      operator: In
                      values:
                      - maxtext-multislice-105
                  topologyKey: MultisliceGroup
              podAntiAffinity:
                requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchExpressions:
                    - key: jobset.sigs.k8s.io/jobset-name
                      operator: NotIn
                      values:
                      - maxtext-multislice-105
                  namespaceSelector:
                    matchExpressions:
                    - key: jobset.sigs.k8s.io/jobset-name
                      operator: Exists
                  topologyKey: MultisliceGroup
            containers:
            - command:
              - python3
              - MaxText/train.py
              - MaxText/configs/base.yml
              - run_name=maxtext-multisclice-105
              - steps=100
              - dataset_path=gs://jk-gke-aiml-repository/datasets
              - base_output_directory=gs://jk-gke-aiml-repository/runs
              env:
              - name: LIBTPU_INIT_ARGS
                value: --xla_tpu_enable_megascale_barrier=true
              image: gcr.io/jk-mlops-dev/maxtext-runner-image
              name: jax-tpu
              ports:
              - containerPort: 8471
              - containerPort: 8080
              resources:
                limits:
                  google.com/tpu: 4
              securityContext:
                privileged: true
            dnsPolicy: ClusterFirstWithHostNet
            hostNetwork: true
            nodeSelector:
              MultisliceGroupSize: "2"
              cloud.google.com/gke-tpu-accelerator: tpu-v4-podslice
              cloud.google.com/gke-tpu-topology: 2x2x2
            serviceAccount: cloud-tpu-sa
